spring.application.name=tecnobooks

# ---------------------------------
# Configuración de la base de datos
# ---------------------------------

# Nuestra base de datos se llama "tecnobooks".
spring.datasource.url=jdbc:mysql://localhost:3306/tecnobooks
spring.datasource.username=root
spring.datasource.password=

# --------------------------------------------------------
# Definimos el driver de MySQL 8 para conectarnos a la BD.
# --------------------------------------------------------

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ------------------------------
# Configuración de JPA-Hibernate
# ------------------------------

# Definiremos lo que Hibernate hará con nuestra BD al iniciar la aplicación:
# update: 
#    Si la tabla no existe, Hibernate la creará. 
#    Si la tabla existe, Hibernate intentará actualizarla según los cambios en las entidades. 
#    Nunca borra datos existentes, pero puede modificar la estructura de las tablas.
# create:
#    Hibernate borrará la tabla si existe y la volverá a crear según las entidades.
spring.jpa.hibernate.ddl-auto=update

# Muestra el código SQL generado por Hibernate en la consola.
spring.jpa.show-sql=true

# Muestra el código SQL generado por Hibernate en la consola de manera más legible.
spring.jpa.properties.hibernate.format_sql=true

# Configuración del dialecto de Hibernate para MySQL.
# Cada motor (MySQL, PostgreSQL, Oracle, etc.) tiene su propio dialecto
# con el cual Hibernate genera SQL específico para ese motor.
# Aparentemente, existe un dialecto para cada versión de MySQL, pero en este caso,
# usaremos el dialecto genérico de MySQL, pues no reconoce MySQL8Dialect (tira un error
# al intentar iniciar la aplicación).
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect